### ISSUE TITLE
problem with active path

### ISSUE THREAD

**Issue by MaraRue** [sg-s/condalab#2]
>> conda.getenv

Undefined function or variable 'active_path'.

Error in conda.getenv (line 66)
				if active_path == i

**Comment by sg-s** [comment]
this is linked to the fact that anaconda is sometimes installed in `/` instead of `~/`

**Comment by craigim** [comment]
This also happens when there is no active environment. I solved this by adding

```matlab
active_path = 0;
```
at line 72. If no environment is active, then none of them get a star.

**Comment by sg-s** [comment]
you should pull from master -- this is done ina  totally different way now, and the user is asked for a path to conda

**Comment by craigim** [comment]
I did pull from master. I got the exact same error as the OP, but apparently I got it for a different reason. I think it's because you hard-coded the file separator instead of using `fullfile` or `filesep`.

**Comment by sg-s** [comment]
all '/' replaced with filesep now -- @craigim are you on windows? i did not image this would work on windows.

**Comment by craigim** [comment]
@sg-s I had to make some minor tweaks (such as the path ones I mentions), but I now call it from my `startup.m` to initialize my python environment. I'm running R2018b on a Windows 10 machine. I will try to figure out how to submit a pull request if you want to test out my changes in Linux.

**Comment by sg-s** [comment]
i've included 

```
active_path = 0;
```

in master now, so it should work for you
