### ISSUE TITLE
Did it work on Anaconda Window 10?

### ISSUE THREAD

**Issue by hammad2008** [sg-s/condalab#8]
Hello i have MATLAB 2022a I have a code in Pytorch in Anaconda environment i want to run it in MATLAB Can anyone help me with that?

**Comment by sg-s** [comment]
i have no idea -- i do not use windows. please try and report back! happy to help debug

**Comment by hammad2008** [comment]
I am getting this error while running on Window 10 MATLAB 2022a


Error using __init__><module>
Python Error: OSError: [WinError 127] The specified procedure could not be found. Error loading
"C:\Users\DELL\anaconda3\envs\myenv\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.

Error in <string>><module> (line 1)

**Comment by hammad2008** [comment]
@sg-s  Can you please modified it to run on Window?

**Comment by sg-s** [comment]
looks like an error with torch, no?

**Comment by hammad2008** [comment]
No, i have the torch version 1.12 with cudatoolkit 11.3

@sg-s  I think If you modified it for window it will be a great contribution for us.

**Comment by sg-s** [comment]
well there's little for me to do. you have to give me more information. what did you run? how did you install it? what did you do?

```
"C:\Users\DELL\anaconda3\envs\myenv\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
                                                      ^^^^
```

this is a torch error

**Comment by hammad2008** [comment]
@sg-s  I just download your repo add to the path and give this path "C:\Users\DELL\anaconda3\envs\myenv\python.exe"
and type Command  conda init but it does not work.

**Comment by sg-s** [comment]
did you do this?

https://github.com/sg-s/condalab#installation

please follow the instructions here

https://github.com/sg-s/condalab#usage

**Comment by hammad2008** [comment]
@sg-s i follow these steps but your code is not running on window 10
conda env list  command shows nothing

**Comment by hammad2008** [comment]
@sg-s  **which conda** command does not work on window 10

**Comment by sg-s** [comment]
https://www.shellhacks.com/windows-which-equivalent-cmd-powershell/

**Comment by hammad2008** [comment]
@sg-s  i also used where command but its not working on window 10

**Comment by hammad2008** [comment]
@sg-s  Can you please upload a tutorial or demo video how to run it on window 
I have matlab 2022a

**Comment by hammad2008** [comment]
@sg-s  did you closed this issue?
